[net]
git-fetch-with-cli = true
[registries.rsproxy]
index = 'https://rsproxy.cn/crates.io-index'
[source.crates-io]
replace-with = 'rsproxy'

[source.rsproxy]
registry = 'https://rsproxy.cn/crates.io-index'

[source.rsproxy-sparse]
registry = 'sparse+https://rsproxy.cn/index/'
