export const enum IpcEvents {
    CHECK_UPDATE = "CHECK_UPDATE",
    OPEN_SETTINGS = "OPEN_SETTINGS",
    OPEN_ABOUT = "OPEN_ABOUT",
    OPEN_PLUGIN_MANAGER = "OPEN_PLUGIN_MANAGER",
    SET_THEME_COLOR = "SET_THEME_COLOR",
    SET_ALWAYS_ON_TOP = "SET_ALWAYS_ON_TOP",
    GET_ALWAYS_ON_TOP = "GET_ALWAYS_ON_TOP"
}
